server {
	listen		8080;
	host		localhost;
	root		www/public;
	index		index.html;

	location /cgi-bin {
		allowed_methods		GET POST;
		cgi_extension		.py;
		cgi_interpreter		/usr/bin/python3;
		root				cgi-bin;
    }
}
