http {
	server {
		listen		127.0.0.1:8080;
		server_name	webserv;

		root		www/public;
		index		webserv.html;

		client_max_body_size 10M;

		error_page 404 www/errors/404.html;

		location / {
			allow_methods	GET;
			autoindex 		off;
		}
	}

	server {
		listen		127.0.0.1:8080;
		server_name	localhost;

		root		www/public;
		index		index.html;

		client_max_body_size 10M;

		error_page 404 www/errors/404.html;
		error_page 405 www/errors/405.html;

		location / {
			allow_methods	GET;
			autoindex 		off;
		}

		location /cgi-bin {
			allow_methods		GET POST;
			cgi_extension		.py;
			cgi_interpreter		/usr/bin/python3;
			root				cgi-bin;
		}

		location /cgi-bash {
			allow_methods		GET POST;
			cgi_extension		.sh;
			cgi_interpreter		/bin/bash;
			root				cgi-bin;
	    }

		location /admin {
			allow_methods	GET;
			root			www/admin;
			autoindex		on;
		}

		location /data {
			allow_methods	POST;
			root			www/data;
		}

		location /uploads {
			allow_methods	GET POST DELETE;
			root			www/uploads;
			upload_dir		www/uploads;
		}
	}
}
