http {
	server {
		listen		127.0.0.1:8080;
		server_name	webserv;

		root		www/public;
		root		www/private;
		index		index.html                 # Missing semicolon V

		client_max_body_size -10M;             # Invalid value V

		error_page 200 www/errors/404.html;    # Invalid error code V
		error_page 405 www/errors/200.html;    # Non existing page  V

		location / {
			allow_methods	GET;
			allow_methods	GET;
			autoindex 		off;
		}

		location dashboard {                   # Invalid location path V
			allow_methods	GET;
			autoindex 		off;
		}

		location /cgi-bin {
			allow_methods		GET POST;
			cgi_extension		.py;
			cgi_interpreter		/usr/bin/pyth; # Non existing executable V
			root				cgi-bin;
		}

		location /cgi-bash {
			allow_methods		GET POST;
			cgi_extension		.sh;
			cgi_interpreter;                   # Missing value V
			root				cgi-bin;
	    }

		location /admin {
			allow_methods	GET LAUNCH;       # Invalid method V
			cgi_extension	.sh;              # Missing cgi_interpreter V
			root			www/admin;
			autoindex		true;             # Invalid autoindex value V
		}

		location /data {
			allow_methods	POST;
			root			www/data;
		}

		location /uploads {
			allow_methods	GET POST DELETE;
			root			www/uploads;
			upload_dir		www/uploads;
		}
	}
	server {
		listen		127.0.0.2:8080;          # Same port same server_name V (checked at the end of the parsing)
		server_name	webserv;

		root		www/public;
		index		index.html;

		client_max_body_size 10G;            # Bigger than default max body size limit V

		error_page 404 www/errors/404.html;
	}
	server {
		listen		127.0.0.3abc:8080;          # Non numeric character in host V
		server_name	webserv;

		root		www/public;
		index		index.html;

		client_max_body_size 10M;

		error_page 404 www/errors/404.html;
	}
	server {
		listen		127.0.0.2:8080abc;          # Non numeric character in port V
		server_name	webs:erv;                   # Invalid server name V

		root		www/public;
		index		index.html;

		client_max_body_size 10M;

		error_page 404 www/errors/404.html;
	}
	server {
		listen		127.0.0.3:80;              # Root reserved port V
		server_name	first second third;        # Multiples server_name V

		root		www/public;
		index		index.html;

		client_max_body_size 10M;

		error_page 403 404 www/errors/404.html; # Multiples errros codes for a single page V
	}                                         # Missing closing braces V
